### ISSUE TITLE
Header is not writing in xlsx format 

### ISSUE THREAD

**Issue by shashi4414** [ZuInnoTe/hadoopoffice#13]
We are not able to add header information into the excel which we are writing using package hadoopoffice.
Is there any options to write the headers to output excel file, Please help me to do the same
 
df.repartition(1).select("*").write().format("org.zuinnote.spark.office.excel")
                            .option("write.locale.bcp47", "de")
                                   .save(fileAbsolutePath);
I have also tried with following. 
.option("useHeader", "true")
.option("Header", "true")
.option("inferSchema", "true")

**Comment by jornfranke** [comment]
Hi,

thank you for the comment. The options do not work, because they do not exist (cf. list of options here: https://github.com/ZuInnoTe/hadoopoffice/wiki/Hadoop-File-Format).

What you are trying to achieve is possible, but keep in mind that in Excel the concept of a header does not exist, but the header is part of the data. This is how you can achieve it:
* Convert your dataframe a into a dataframe of type SpreadSheetCellDOA (cf. https://github.com/ZuInnoTe/spark-hadoopoffice-ds/blob/master/README.md#writing).
* Create a dataframe h of type SpreadSheetCellDAO which contains the headers (hint use the method columns on dataframe a https://spark.apache.org/docs/1.6.3/api/java/org/apache/spark/sql/DataFrame.html#columns())
* join a to h
* write it as usual

Please let me know if you have further questions.

**Comment by jornfranke** [comment]
An alternative could be implemented in the spark hadoopoffice datasource (here: https://github.com/ZuInnoTe/spark-hadoopoffice-ds/blob/master/src/main/scala/org/zuinnote/spark/office/excel/ExcelOutputWriter.scala), where we could read the option write.spark.useHeader and if this option is true and if it is true then we add in the first row the headers (to be determined via row.schema.fieldnames (tbc).

of course we need to add unit tests.

It could be part of milestone 1.0.4

**Comment by jornfranke** [comment]
It has been enhanced including tests. You can find the source code here: https://github.com/ZuInnoTe/spark-hadoopoffice-ds
You can build your own version or wait for the next release (ca. end of July).

**Comment by shashi4414** [comment]
Thanks for the quick feedback we will work an this code  and we expecting added feature in 1.0.4.
 Good work and you are tests will helps.

**Comment by jornfranke** [comment]
If you have the chance to give feedback before release it would be appreciated.

**Comment by jornfranke** [comment]
added in version 1.0.4

**Comment by shashi4414** [comment]
hi jornfranke 
we are using latest version 1.0.4 to write in to excel file it is working good and you solved previous version issu.
but the header is still not writing.. 
please help me any changes an my code 
below is the code for writing 
df.write()
.format("org.zuinnote.spark.office.excel")
.option("write.locale.bcp47", "us") 
.save("D:\\xls\\excelWrite.xlsx");

**Comment by jornfranke** [comment]
You forgot the option to write the header .option("write.spark.useHeader",true)

It should work because this is tested as part of every build automatically
