### ISSUE TITLE
“scala.MatchError: 1 (of class java.lang.Long)”  Exception 

### ISSUE THREAD

**Issue by shashi4414** [ZuInnoTe/hadoopoffice#15]
We are getting exception “scala.MatchError: 1 (of class java.lang.Long)” when we write the data frame to excel, looks like the package “org.zuinnote.spark.office.excel” not able to handle null values present in the Dataset.
It is almost impossible to avoid null values in dataset, because some attribute can contain null values. Can someone let us know how to write dataset to excel which contain null values.

Code used during Write
matachedProcessedRecords.repartition(1).select("*").write()
         .format("org.zuinnote.spark.office.excel")
         .option("write.locale.bcp47", "de")
         .save(fileAbsolutePath);

Code used during read code.
dataFileContent=sqlContext.read().format("com.crealytics.spark.excel")
        .option("location", location+fileName)
        .option("useHeader", "true")
        .option("inferSchema", "false")
        .option("treatEmptyValuesAsNulls", "true")
         .option("addColorColumns", "false")
         .load();

**Comment by jornfranke** [comment]
Why do you use another datasource to read the data in Excel?
Anyway...
Null values are normally treated by the application you write because there can be different underlying business logic to handle them ... for example they can be represented as empty cell, as 0 and as the string "null".
I recommend to look at the second option provided by hadoopoffice (using SpreadsheetCellDAO) and a simple mapping. This will solve all your issues.

Of course we can add in later versions a specific null handling (e.g. Map it to an empty excel cell), but for your case hadoopoffice provided all that you need already.

Please let me know if you have further questions.

**Comment by shashi4414** [comment]
thanks for the response.
We found reading the excel by package “org.zuinnote.spark.office.excel” bit cumbersome .. hence we are using other package. We are not finding much example in java using this class spreadSheetCellDAO to write to excel, if you share some of the link it will be of great help thanks

**Comment by jornfranke** [comment]
Well reading it should not be cumbersome if you have Spark knowledge. 
It allows you a lot of flexible to handle nulls etc.

I do not recommend merging of both because then you end up with different versions of Apache POI leading to issues bugs.

An example is provided in the hadoopoffice wiki and for the datasource in readme.md Let me know what you do not understand ....

Maybe you can also elaborate more on your use case. What are you doing with the data?

**Comment by jornfranke** [comment]
Additionally on your use case what you do with the data, can you describe how the Excel file looks like?

**Comment by jornfranke** [comment]
Example for using SpreadSheetCellDAO can be found here: https://github.com/ZuInnoTe/hadoopoffice/wiki/Write-an-Excel-document-using-the-Spark2-datasource-API

and here is some documentation:
https://github.com/ZuInnoTe/spark-hadoopoffice-ds#writing

**Comment by jornfranke** [comment]
I discovered the issue you mentioned was related to something else. It has been fixed including tests. You can find the source code here: https://github.com/ZuInnoTe/spark-hadoopoffice-ds
You can build your own version or wait for the next release (ca. end of July).

**Comment by jornfranke** [comment]
Hi, most likely version 1.0.4 will be released on the 31st. It will not only include this fix, but also the option read.spark.simpleMode (that means it automatically detects the schema in Excel and creates the DataFrame with Spark datatypes) and read.spark.useHeader (to name the column in a dataframe after the first row in Excel)

**Comment by jornfranke** [comment]
fixed with released version 1.0.4
